// Reads forge artifacts from packages/contracts/out and emits a committed TS module
// with { abi, bytecode } for each contract, so the SDK does not depend on the
// gitignored out/ directory at runtime/test time.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../../contracts/out");
const dest = resolve(here, "../src/abi.generated.ts");

const CONTRACTS = ["MockUSDC", "LiquidityPool", "InvoiceRegistry", "FactoringController"];

function load(name) {
  const json = JSON.parse(readFileSync(resolve(outDir, `${name}.sol/${name}.json`), "utf8"));
  const bytecode = json.bytecode?.object ?? json.bytecode;
  if (!json.abi || !bytecode) throw new Error(`Missing abi/bytecode for ${name}; run 'forge build' first`);
  return { abi: json.abi, bytecode };
}

const banner = "// AUTO-GENERATED by scripts/gen-abi.mjs. Do not edit by hand.\n// Regenerate after contract changes: pnpm -F @anticipo/shared gen:abi\n";
let body = banner + "\n";
for (const name of CONTRACTS) {
  const { abi, bytecode } = load(name);
  body += `export const ${name} = {\n  abi: ${JSON.stringify(abi)} as const,\n  bytecode: ${JSON.stringify(bytecode)} as \`0x\${string}\`,\n};\n\n`;
}
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, body);
console.log(`Wrote ${dest} (${CONTRACTS.join(", ")})`);
